/*
 * This file is generated by jOOQ.
*/
package com.jooq.data.tables;


import com.jooq.data.Public;
import com.jooq.data.tables.records.TestRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends TableImpl<TestRecord> {

    private static final long serialVersionUID = 82646543;

    /**
     * The reference instance of <code>public.test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestRecord> getRecordType() {
        return TestRecord.class;
    }

    /**
     * The column <code>public.test.name</code>.
     */
    public final TableField<TestRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CHAR.length(10), this, "");

    /**
     * The column <code>public.test.sex</code>.
     */
    public final TableField<TestRecord, Integer> SEX = createField("sex", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.test</code> table reference
     */
    public Test() {
        this("test", null);
    }

    /**
     * Create an aliased <code>public.test</code> table reference
     */
    public Test(String alias) {
        this(alias, TEST);
    }

    private Test(String alias, Table<TestRecord> aliased) {
        this(alias, aliased, null);
    }

    private Test(String alias, Table<TestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Test as(String alias) {
        return new Test(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Test rename(String name) {
        return new Test(name, null);
    }
}
