/*
 * This file is generated by jOOQ.
*/
package com.jooq.data.tables;


import com.jooq.data.Keys;
import com.jooq.data.Public;
import com.jooq.data.tables.records.UrlsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Urls extends TableImpl<UrlsRecord> {

    private static final long serialVersionUID = -461514457;

    /**
     * The reference instance of <code>public.urls</code>
     */
    public static final Urls URLS = new Urls();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UrlsRecord> getRecordType() {
        return UrlsRecord.class;
    }

    /**
     * The column <code>public.urls.id</code>.
     */
    public final TableField<UrlsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('urls_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.urls.url</code>.
     */
    public final TableField<UrlsRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.urls.plist</code>.
     */
    public final TableField<UrlsRecord, Long[]> PLIST = createField("plist", org.jooq.impl.SQLDataType.BIGINT.getArrayDataType(), this, "");

    /**
     * The column <code>public.urls.olist</code>.
     */
    public final TableField<UrlsRecord, Long[]> OLIST = createField("olist", org.jooq.impl.SQLDataType.BIGINT.getArrayDataType(), this, "");

    /**
     * The column <code>public.urls.llist</code>.
     */
    public final TableField<UrlsRecord, Long[]> LLIST = createField("llist", org.jooq.impl.SQLDataType.BIGINT.getArrayDataType(), this, "");

    /**
     * Create a <code>public.urls</code> table reference
     */
    public Urls() {
        this("urls", null);
    }

    /**
     * Create an aliased <code>public.urls</code> table reference
     */
    public Urls(String alias) {
        this(alias, URLS);
    }

    private Urls(String alias, Table<UrlsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Urls(String alias, Table<UrlsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UrlsRecord, Long> getIdentity() {
        return Keys.IDENTITY_URLS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UrlsRecord> getPrimaryKey() {
        return Keys.URLS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UrlsRecord>> getKeys() {
        return Arrays.<UniqueKey<UrlsRecord>>asList(Keys.URLS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Urls as(String alias) {
        return new Urls(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Urls rename(String name) {
        return new Urls(name, null);
    }
}
