/*
 * This file is generated by jOOQ.
*/
package com.jooq.data.tables.records;


import com.jooq.data.tables.Persons;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonsRecord extends UpdatableRecordImpl<PersonsRecord> implements Record3<Long, String, Long[]> {

    private static final long serialVersionUID = -1961074290;

    /**
     * Setter for <code>public.persons.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.persons.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.persons.person</code>.
     */
    public void setPerson(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.persons.person</code>.
     */
    public String getPerson() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.persons.ulist</code>.
     */
    public void setUlist(Long... value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.persons.ulist</code>.
     */
    public Long[] getUlist() {
        return (Long[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long[]> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Persons.PERSONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Persons.PERSONS.PERSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long[]> field3() {
        return Persons.PERSONS.ULIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPerson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long[] value3() {
        return getUlist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsRecord value2(String value) {
        setPerson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsRecord value3(Long... value) {
        setUlist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsRecord values(Long value1, String value2, Long[] value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonsRecord
     */
    public PersonsRecord() {
        super(Persons.PERSONS);
    }

    /**
     * Create a detached, initialised PersonsRecord
     */
    public PersonsRecord(Long id, String person, Long[] ulist) {
        super(Persons.PERSONS);

        set(0, id);
        set(1, person);
        set(2, ulist);
    }
}
