/*
 * This file is generated by jOOQ.
*/
package com.jooq.data.tables.records;


import com.jooq.data.tables.Urls;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UrlsRecord extends UpdatableRecordImpl<UrlsRecord> implements Record5<Long, String, Long[], Long[], Long[]> {

    private static final long serialVersionUID = 416825715;

    /**
     * Setter for <code>public.urls.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.urls.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.urls.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.urls.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.urls.plist</code>.
     */
    public void setPlist(Long... value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.urls.plist</code>.
     */
    public Long[] getPlist() {
        return (Long[]) get(2);
    }

    /**
     * Setter for <code>public.urls.olist</code>.
     */
    public void setOlist(Long... value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.urls.olist</code>.
     */
    public Long[] getOlist() {
        return (Long[]) get(3);
    }

    /**
     * Setter for <code>public.urls.llist</code>.
     */
    public void setLlist(Long... value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.urls.llist</code>.
     */
    public Long[] getLlist() {
        return (Long[]) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Long[], Long[], Long[]> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Long[], Long[], Long[]> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Urls.URLS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Urls.URLS.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long[]> field3() {
        return Urls.URLS.PLIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long[]> field4() {
        return Urls.URLS.OLIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long[]> field5() {
        return Urls.URLS.LLIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long[] value3() {
        return getPlist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long[] value4() {
        return getOlist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long[] value5() {
        return getLlist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UrlsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UrlsRecord value2(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UrlsRecord value3(Long... value) {
        setPlist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UrlsRecord value4(Long... value) {
        setOlist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UrlsRecord value5(Long... value) {
        setLlist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UrlsRecord values(Long value1, String value2, Long[] value3, Long[] value4, Long[] value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UrlsRecord
     */
    public UrlsRecord() {
        super(Urls.URLS);
    }

    /**
     * Create a detached, initialised UrlsRecord
     */
    public UrlsRecord(Long id, String url, Long[] plist, Long[] olist, Long[] llist) {
        super(Urls.URLS);

        set(0, id);
        set(1, url);
        set(2, plist);
        set(3, olist);
        set(4, llist);
    }
}
