/*
 * This file is generated by jOOQ.
*/
package com.jooq.data;


import com.jooq.data.tables.Locations;
import com.jooq.data.tables.Organizations;
import com.jooq.data.tables.Persons;
import com.jooq.data.tables.Urls;
import com.jooq.data.tables.records.LocationsRecord;
import com.jooq.data.tables.records.OrganizationsRecord;
import com.jooq.data.tables.records.PersonsRecord;
import com.jooq.data.tables.records.UrlsRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<LocationsRecord, Long> IDENTITY_LOCATIONS = Identities0.IDENTITY_LOCATIONS;
    public static final Identity<OrganizationsRecord, Long> IDENTITY_ORGANIZATIONS = Identities0.IDENTITY_ORGANIZATIONS;
    public static final Identity<PersonsRecord, Long> IDENTITY_PERSONS = Identities0.IDENTITY_PERSONS;
    public static final Identity<UrlsRecord, Long> IDENTITY_URLS = Identities0.IDENTITY_URLS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LocationsRecord> LOCATIONS_PKEY = UniqueKeys0.LOCATIONS_PKEY;
    public static final UniqueKey<OrganizationsRecord> ORGANIZATIONS_PKEY = UniqueKeys0.ORGANIZATIONS_PKEY;
    public static final UniqueKey<PersonsRecord> PERSONS_PKEY = UniqueKeys0.PERSONS_PKEY;
    public static final UniqueKey<UrlsRecord> URLS_PKEY = UniqueKeys0.URLS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<LocationsRecord, Long> IDENTITY_LOCATIONS = createIdentity(Locations.LOCATIONS, Locations.LOCATIONS.ID);
        public static Identity<OrganizationsRecord, Long> IDENTITY_ORGANIZATIONS = createIdentity(Organizations.ORGANIZATIONS, Organizations.ORGANIZATIONS.ID);
        public static Identity<PersonsRecord, Long> IDENTITY_PERSONS = createIdentity(Persons.PERSONS, Persons.PERSONS.ID);
        public static Identity<UrlsRecord, Long> IDENTITY_URLS = createIdentity(Urls.URLS, Urls.URLS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<LocationsRecord> LOCATIONS_PKEY = createUniqueKey(Locations.LOCATIONS, "locations_pkey", Locations.LOCATIONS.ID);
        public static final UniqueKey<OrganizationsRecord> ORGANIZATIONS_PKEY = createUniqueKey(Organizations.ORGANIZATIONS, "organizations_pkey", Organizations.ORGANIZATIONS.ID);
        public static final UniqueKey<PersonsRecord> PERSONS_PKEY = createUniqueKey(Persons.PERSONS, "persons_pkey", Persons.PERSONS.ID);
        public static final UniqueKey<UrlsRecord> URLS_PKEY = createUniqueKey(Urls.URLS, "urls_pkey", Urls.URLS.ID);
    }
}
