/*
 * This file is generated by jOOQ.
*/
package com.jooq.data;


import com.jooq.data.tables.Locations;
import com.jooq.data.tables.Organizations;
import com.jooq.data.tables.Persons;
import com.jooq.data.tables.Test;
import com.jooq.data.tables.Urls;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1955767825;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.locations</code>.
     */
    public final Locations LOCATIONS = com.jooq.data.tables.Locations.LOCATIONS;

    /**
     * The table <code>public.organizations</code>.
     */
    public final Organizations ORGANIZATIONS = com.jooq.data.tables.Organizations.ORGANIZATIONS;

    /**
     * The table <code>public.persons</code>.
     */
    public final Persons PERSONS = com.jooq.data.tables.Persons.PERSONS;

    /**
     * The table <code>public.test</code>.
     */
    public final Test TEST = com.jooq.data.tables.Test.TEST;

    /**
     * The table <code>public.urls</code>.
     */
    public final Urls URLS = com.jooq.data.tables.Urls.URLS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.LOCATIONS_ID_SEQ,
            Sequences.ORGANIZATIONS_ID_SEQ,
            Sequences.PERSONS_ID_SEQ,
            Sequences.URLS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Locations.LOCATIONS,
            Organizations.ORGANIZATIONS,
            Persons.PERSONS,
            Test.TEST,
            Urls.URLS);
    }
}
