/*
 * This file is generated by jOOQ.
*/
package com.jooq.data;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.locations_id_seq</code>
     */
    public static final Sequence<Long> LOCATIONS_ID_SEQ = new SequenceImpl<Long>("locations_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.organizations_id_seq</code>
     */
    public static final Sequence<Long> ORGANIZATIONS_ID_SEQ = new SequenceImpl<Long>("organizations_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.persons_id_seq</code>
     */
    public static final Sequence<Long> PERSONS_ID_SEQ = new SequenceImpl<Long>("persons_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.urls_id_seq</code>
     */
    public static final Sequence<Long> URLS_ID_SEQ = new SequenceImpl<Long>("urls_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
